// ...existing code...
const waterMaterial = new THREE.MeshPhongMaterial({
    // ...existing code...
    opacity: 0.8, // Increased opacity
    transparent: true,
    // ...existing code...
});
// ...existing code...
